### ISSUE TITLE
Dispose HttpClient

### ISSUE THREAD

**Issue by 7-bit** [pssst/pssst#3]
At the moment the HttpClient used in Communication is not disposed when done with using it.

**Comment by cuhsat** [comment]
You might probably use a destructor (https://msdn.microsoft.com/en-us/library/66x5fx1b.aspx) or refactor the code to make use of `using` blocks?

```
public ~Communication() {
  _http.Dispose();
}
```

**Comment by 7-bit** [comment]
I think refactoring the code to utilize the `using` blocks is the way to go, since the base class `HttpMessageInvoker` implements `IDisposable` (http://referencesource.microsoft.com/#System.Net.Http/System/Net/Http/HttpMessageInvoker.cs,ae9972bd3bb5aa7b).

**Comment by cuhsat** [comment]
Yeah, I think this is cleanest way.
